version: '3.1'
services:
 spacedungeon:
  container_name: spacedungeon
  restart: always
  build: .
  ports:
   - "8080:8080"
  links:
   - mongodb-spacedungeon
  depends_on:
   - mongodb-spacedungeon

 mongodb-spacedungeon:
  image: mongo:latest
  container_name: mongodb-spacedungeon
  restart: always
  volumes:
   - /var/mongodb-spacedungeon:/data/db
   - mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: example
   MONGO_INITDB_DATABASE: spacedungeon1
